name: interpretable-ai
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _anaconda_depends=2019.03
  - alabaster=0.7.12
  - anaconda=custom=py37_1
  - anaconda-client=1.7.2=py37_0
  - anaconda-project=0.8.4=py_0
  - asn1crypto=1.2.0=py37_0
  - astroid=2.3.2=py37_0
  - astropy=3.2.3
  - atomicwrites=1.3.0=py37_1
  - attrs=19.3.0=py_0
  - babel=2.7.0=py_0
  - backcall=0.1.0=py37_0
  - backports=1.0=py_2
  - backports.os=0.1.1=py37_0
  - backports.shutil_get_terminal_size=1.0.0=py37_2
  - beautifulsoup4=4.8.1=py37_0
  - bitarray=1.0.1
  - bkcharts=0.2=py37_0
  - blas=1.0=mkl
  - bleach=3.1.0=py37_0
  - blosc=1.16.3
  - bokeh=1.4.0=py37_0
  - boto=2.49.0=py37_0
  - bottleneck=1.2.1
  - bzip2=1.0.8
  - ca-certificates=2020.1.1=0
  - cairo=1.14.12
  - certifi=2020.4.5.1=py37_0
  - cffi=1.13.1
  - chardet=3.0.4=py37_1003
  - cloudpickle=1.2.2=py_0
  - clyent=1.2.2=py37_1
  - colorama=0.4.1=py37_0
  - contextlib2=0.6.0=py_0
  - cryptography=2.8
  - curl=7.65.3
  - cycler=0.10.0=py37_0
  - cython=0.29.13
  - cytoolz=0.10.0
  - dask=2.6.0=py_0
  - dask-core=2.6.0=py_0
  - dbus=1.13.12
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - distributed=2.6.0=py_0
  - docutils=0.15.2=py37_0
  - entrypoints=0.3=py37_0
  - et_xmlfile=1.0.1=py37_0
  - expat=2.2.6
  - fastcache=1.1.0
  - ffmpeg=4.0
  - filelock=3.0.12=py_0
  - flask=1.1.1=py_0
  - fontconfig
  - freetype=2.9.1
  - fribidi=1.0.5
  - fsspec=0.5.2=py_0
  - get_terminal_size=1.0.0
  - gettext=0.19.8.1
  - gevent=1.4.0
  - glib=2.63.1
  - glob2=0.7=py_0
  - gmp=6.1.2
  - gmpy2=2.0.8
  - graphite2=1.3.13
  - graphviz=2.40.1
  - greenlet=0.4.15
  - h5py=2.8.0
  - harfbuzz=1.8.8
  - hdf5=1.10.2
  - heapdict=1.0.1=py_0
  - html5lib=1.0.1=py37_0
  - icu=58.2
  - idna=2.8=py37_0
  - imageio=2.6.1=py37_0
  - imagesize=1.1.0=py37_0
  - importlib_metadata=0.23=py37_0
  - intel-openmp=2019.4
  - ipykernel=5.1.3=py37h39e3cac_0
  - ipython=7.9.0=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.5.1=py_0
  - isort=4.3.21=py37_0
  - itsdangerous=1.1.0=py37_0
  - jasper=2.0.14
  - jbig=2.1
  - jdcal=1.4.1=py_0
  - jedi=0.15.1=py37_0
  - jinja2=2.10.3=py_0
  - joblib=0.14.0=py_0
  - jpeg=9b
  - json5=0.8.5=py_0
  - jsonschema=3.1.1=py37_0
  - jupyter=1.0.0=py37_7
  - jupyter_client=6.1.2
  - jupyter_console=6.0.0=py37_0
  - jupyter_core=4.6.1=py37_0
  - jupyterlab=1.1.4=pyhf63ae98_0
  - jupyterlab_server=1.0.6=py_0
  - keyring=18.0.0=py37_0
  - kiwisolver=1.1.0
  - krb5=1.16.1
  - lazy-object-proxy=1.4.3
  - libarchive=3.3.3
  - libcurl=7.65.3
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libiconv=1.15
  - liblief=0.9.0
  - libopencv=3.4.2
  - libopus=1.3.1
  - libpng=1.6.37
  - libsodium=1.0.16
  - libssh2=1.8.2
  - libtiff=4.1.0
  - libvpx=1.7.0
  - libxml2=2.9.9
  - libxslt=1.1.33
  - llvmlite=0.30.0
  - locket=0.2.0=py37_1
  - lxml=4.4.1
  - lz4-c=1.8.1.2
  - lzo=2.10
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - mccabe=0.6.1=py37_1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - mock=3.0.5=py37_0
  - more-itertools=7.2.0=py37_0
  - mpc=1.1.0
  - mpfr=4.0.1
  - mpmath=1.1.0=py37_0
  - msgpack-python=0.6.1
  - multipledispatch=0.6.0=py37_0
  - nbconvert=5.6.1=py37_0
  - nbformat=5.0.3
  - ncurses=6.1
  - networkx=2.4=py_0
  - ninja=1.9.0
  - nltk=3.4.5=py37_0
  - nose=1.3.7=py37_2
  - notebook=6.0.1=py37_0
  - numba=0.46.0
  - numexpr=2.7.0
  - numpy=1.17.3
  - numpy-base=1.17.3
  - numpydoc=0.9.1=py_0
  - olefile=0.46=py37_0
  - opencv=3.4.2=py37h6fd60c2_1
  - openpyxl=3.0.0=py_0
  - openssl=1.1.1g
  - packaging=19.2=py_0
  - pandas=0.25.2
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - pango
  - parso=0.5.1=py_0
  - partd=1.0.0=py_0
  - path.py=12.0.1=py_0
  - pathlib2=2.3.5=py37_0
  - patsy=0.5.1=py37_0
  - pcre=8.43
  - pep8=1.7.1=py37_0
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pillow=6.2.1
  - pip=19.3.1=py37_0
  - pixman=0.38.0
  - pkginfo=1.5.0.1=py37_0
  - pluggy=0.13.0=py37_0
  - ply=3.11=py37_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.10=py_0
  - psutil=5.6.3
  - ptyprocess=0.6.0=py37_0
  - py=1.8.0=py37_0
  - py-lief=0.9.0
  - py-opencv=3.4.2
  - pycodestyle=2.5.0=py37_0
  - pycosat=0.6.3
  - pycparser=2.19=py37_0
  - pycrypto=2.6.1
  - pycurl=7.43.0.3
  - pydotplus=2.0.2=pyhd1c1de3_3
  - pyflakes=2.1.1=py37_0
  - pygments=2.4.2=py_0
  - pylint=2.4.3=py37_0
  - pyodbc=4.0.27
  - pyopenssl=19.0.0=py37_0
  - pyparsing=2.4.2=py_0
  - pyqt=5.9.2
  - pyrsistent=0.15.4
  - pysocks=1.7.1=py37_0
  - pytables=3.4.4
  - pytest=5.2.2=py37_0
  - pytest-arraydiff=0.3=py37h39e3cac_0
  - pytest-astropy=0.5.0=py37_0
  - pytest-doctestplus=0.4.0=py_0
  - pytest-openfiles=0.4.0=py_0
  - pytest-remotedata=0.3.2=py37_0
  - python=3.7.5
  - python-dateutil=2.8.1=py_0
  - python-libarchive-c=2.8=py37_13
  - pytorch=1.4.0
  - pytz=2019.3=py_0
  - pywavelets=1.0.3
  - pyyaml=5.1.2
  - pyzmq=18.1.0
  - qt=5.9.7
  - qtawesome=0.6.0=py_0
  - qtconsole=4.5.5=py_0
  - qtpy=1.9.0=py_0
  - readline=7.0
  - requests=2.22.0=py37_0
  - rope=0.14.0=py_0
  - ruamel_yaml=0.15.46
  - scikit-image=0.15.0
  - scikit-learn=0.21.3
  - scipy=1.1.0
  - seaborn=0.9.0=py37_0
  - send2trash=1.5.0=py37_0
  - setuptools=41.6.0=py37_0
  - simplegeneric=0.8.1=py37_2
  - singledispatch=3.4.0.3=py37_0
  - sip=4.19.8
  - six=1.12.0=py37_0
  - snappy=1.1.7
  - snowballstemmer=2.0.0=py_0
  - sortedcollections=1.1.2=py37_0
  - sortedcontainers=2.1.0=py37_0
  - soupsieve=1.9.3=py37_0
  - sphinx=2.2.1=py_0
  - sphinxcontrib=1.0=py37_1
  - sphinxcontrib-applehelp=1.0.1=py_0
  - sphinxcontrib-devhelp=1.0.1=py_0
  - sphinxcontrib-htmlhelp=1.0.2=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.2=py_0
  - sphinxcontrib-serializinghtml=1.1.3=py_0
  - sphinxcontrib-websupport=1.1.2=py_0
  - spyder=3.3.6=py37_0
  - spyder-kernels=0.5.2=py37_0
  - sqlalchemy=1.3.10
  - sqlite=3.30.1
  - statsmodels=0.10.1
  - sympy=1.4=py37_0
  - tbb=2019.8
  - tblib=1.5.0=py_0
  - terminado=0.8.3
  - testpath=0.4.2=py37_0
  - tk=8.6.8
  - toolz=0.10.0=py_0
  - torchvision=0.5.0=py37_cpu
  - tornado=6.0.3
  - traitlets=4.3.3=py37_0
  - unicodecsv=0.14.1=py37_0
  - unixodbc=2.3.7
  - urllib3=1.24.2=py37_0
  - wcwidth=0.1.7=py37_0
  - webencodings=0.5.1=py37_1
  - werkzeug=0.16.0=py_0
  - wheel=0.33.6=py37_0
  - widgetsnbextension=3.5.1=py37_0
  - wrapt=1.11.2
  - wurlitzer=1.0.3=py37_0
  - xlrd=1.2.0=py37_0
  - xlsxwriter=1.2.2=py_0
  - xlwt=1.3.0=py37_0
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.3.1
  - zict=1.0.0=py_0
  - zipp=0.6.0=py_0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - anchor-exp==0.0.0.6
    - args==0.1.0
    - blis==0.4.1
    - catalogue==1.0.0
    - click==6.7
    - clint==0.5.1
    - cssselect2==0.3.0
    - cymem==2.0.3
    - floyd-cli==0.11.17
    - future==0.18.2
    - gensim==4.1.2
    - ipdb==0.13.3
    - lime==0.1.1.37
    - marshmallow==2.21.0
    - murmurhash==1.0.2
    - pdfkit==0.6.1
    - pdpbox==0.2.0
    - plac==1.1.3
    - preshed==3.0.2
    - prettytable==0.7.2
    - progressbar==2.5
    - progressbar2==3.47.0
    - pygam==0.8.0
    - python-utils==2.3.0
    - raven==6.10.0
    - reportlab==3.5.42
    - requests-toolbelt==0.9.1
    - scikit-plot==0.3.7
    - shap==0.35.0
    - smart-open==5.2.1
    - spacy==2.2.4
    - srsly==1.0.2
    - svglib==1.0.0
    - tabulate==0.8.7
    - thinc==7.4.0
    - tinycss2==1.0.2
    - tqdm==4.43.0
    - typed-ast==1.4.1
    - wasabi==0.6.0
